# config/hyperparameters.yml

# This file defines the search space for hyperparameter optimization using Hyperopt.
# For details on distributions, see: http://hyperopt.github.io/hyperopt/getting-started/search_spaces/

# --- General Training Parameters ---
max_evals: 50
cv_splits: 5

epochs:
  name: epochs
  dist: quniform
  args: [20, 30, 50]

batch_size:
  name: batch_size
  dist: quniform
  args: [32, 256, 32]

# --- Optimizer Parameters ---
learning_rate:
  name: learning_rate
  dist: loguniform
  args: [-9.2, -4.6] # Corresponds to ~1e-4 to 1e-2 in log space (ln(1e-4), ln(1e-2))

weight_decay:
  name: weight_decay
  dist: loguniform
  args: [-13.8, -6.9] # Corresponds to ~1e-6 to 1e-3 in log space

# --- MDN Specific Parameters ---
n_gaussians:
  name: n_gaussians
  dist: quniform
  args: [2, 10, 1] # Min, Max, Step -> discrete uniform

# --- Network Architecture Parameters ---
# We use hp.choice to select from a set of predefined architectures
core_network_depth:
  name: core_network_depth
  dist: choice
  args:
    - [128, 64] # A 2-layer core network
    - [256, 128, 64] # A 3-layer core network

head_network_depth:
  name: head_network_depth
  dist: choice
  args:
    - [32] # A 1-layer head network
    - [64, 32] # A 2-layer head network
    - [128, 64, 32] # A 2-layer head network